% Tests for QUIC frames
~ parsing
+ Check client initial frames
=
from binascii import unhexlify
from scapy.layers.quic.packets import QuicInitial
from scapy.layers.quic.packets.frames import CryptoFrame, AckFrame
from scapy.packet import NoPayload
from test.quic import CLIENT_INITIAL_BYTES, SERVER_INITIAL_BYTES

= Parse client initial
client_initial = QuicInitial(CLIENT_INITIAL_BYTES)

= Get client initial frames
client_initial_frames = client_initial.get_frames()

= Test client initial frames
assert len(client_initial_frames) == 1

= Test client initial crypto frame
client_initial_crypto_frame = client_initial_frames[0]
assert type(client_initial_crypto_frame) == CryptoFrame
assert client_initial_crypto_frame.frame_type == 0x6
assert client_initial_crypto_frame.offset == 0
assert client_initial_crypto_frame.length == 241
assert client_initial_crypto_frame.crypto_data == unhexlify(
    "010000ed0303ebf8fa56f12939b9584a3896472ec40bb863cfd3e86804fe3a47"
    "f06a2b69484c00000413011302010000c000000010000e00000b6578616d706c"
    "652e636f6dff01000100000a00080006001d0017001800100007000504616c70"
    "6e000500050100000000003300260024001d00209370b2c9caa47fbabaf4559f"
    "edba753de171fa71f50f1ce15d43e994ec74d748002b0003020304000d001000"
    "0e0403050306030203080408050806002d00020101001c000240010039003204"
    "08ffffffffffffffff05048000ffff07048000ffff0801100104800075300901"
    "100f088394c8f03e51570806048000ffff"
)
assert client_initial_crypto_frame.payload == NoPayload()


+ Check server initial frames
= Parse server initial
server_initial = QuicInitial(SERVER_INITIAL_BYTES)

= Get server initial frames
server_initial_frames = server_initial.get_frames()

= Test server initial frames
assert len(server_initial_frames) == 2

= Test server initial ack frame
server_initial_ack_frame = server_initial_frames[0]
assert type(server_initial_ack_frame) == AckFrame
assert server_initial_ack_frame.frame_type == 0x2
assert server_initial_ack_frame.largest_acknowledged == 0
assert server_initial_ack_frame.ack_delay == 0
assert server_initial_ack_frame.ack_range_count == 0
assert server_initial_ack_frame.first_ack_range == 0
assert server_initial_ack_frame.ack_ranges is None
assert server_initial_ack_frame.ect0_count is None
assert server_initial_ack_frame.ect1_count is None
assert server_initial_ack_frame.ecn_ce_count is None
assert server_initial_ack_frame.payload == NoPayload()

= Test server initial crypto frame
server_initial_crypto_frame = server_initial_frames[1]
assert type(server_initial_crypto_frame) == CryptoFrame
assert server_initial_crypto_frame.frame_type == 0x6
assert server_initial_crypto_frame.offset == 0
assert server_initial_crypto_frame.length == 90
assert server_initial_crypto_frame.crypto_data == unhexlify(
    "020000560303eefce7f7b37ba1d1632e96677825ddf73988cfc79825df566dc5"
    "430b9a045a1200130100002e00330024001d00209d3c940d89690b84d08a6099"
    "3c144eca684d1081287c834d5311bcf32bb9da1a002b00020304"
)
assert server_initial_crypto_frame.payload == NoPayload()


+ Padding frame single byte
= Parse one zero byte
from scapy.layers.quic.packets.frames import FrameStorage, PaddingFrame
one_padding = FrameStorage(unhexlify("00"))

= Check only one frame
padding_frames = one_padding.get_frames()
assert len(padding_frames) == 1

= Check that one padding frame
padding_frame = padding_frames[0]
assert type(padding_frame) == PaddingFrame
assert padding_frame.frame_type == 0
assert padding_frame.payload == NoPayload()


+ Padding frames many bytes
= Parse many zero bytes
size = 100
padding = FrameStorage(b"\x00" * size)

= Check correct amount of frames
padding_frames = padding.get_frames()
assert len(padding_frames) == size

= Check these padding frames
for padding_frame in padding_frames:
    assert type(padding_frame) == PaddingFrame
    assert padding_frame.frame_type == 0
    assert padding_frame.payload == NoPayload()


+ Ping frame single byte
= Parse one one byte
from scapy.layers.quic.packets.frames import PingFrame
one_ping = FrameStorage(unhexlify("01"))

= Check only one frame
ping_frames = one_ping.get_frames()
assert len(ping_frames) == 1

= Check that one ping frame
ping_frame = ping_frames[0]
assert type(ping_frame) == PingFrame
assert ping_frame.frame_type == 1
assert ping_frame.payload == NoPayload()


+ Ack frame, case 1: type 0x02, just zero bytes
= Parse the bytes
from scapy.layers.quic.packets.frames import AckFrame
frame_bytes = unhexlify("0200000000")
one_ack = FrameStorage(frame_bytes)

= Check only one frame
frames = one_ack.get_frames()
assert len(frames) == 1

= Check that one ack frame
ack_frame = frames[0]
assert type(ack_frame) == AckFrame
assert ack_frame.frame_type == 2
assert ack_frame.largest_acknowledged == 0
assert ack_frame.ack_delay == 0
assert ack_frame.ack_range_count == 0
assert ack_frame.first_ack_range == 0
assert ack_frame.ack_ranges is None
assert ack_frame.ect0_count is None
assert ack_frame.ect1_count is None
assert ack_frame.ecn_ce_count is None
assert ack_frame.payload == NoPayload()

= Check build equal to start bytes
assert ack_frame.build() == frame_bytes


+ Ack frame, case 2: type 0x02, various bytes
= Parse the bytes
frame_bytes = unhexlify(
    "02"
    + "423f"
    + "8c456789"
    + "cf23456789abcdef"
    + "0f"
    + "00" * 0xf
)
one_ack = FrameStorage(frame_bytes)

= Check only one frame
frames = one_ack.get_frames()
assert len(frames) == 1

= Check that one ack frame
ack_frame = frames[0]
assert type(ack_frame) == AckFrame
assert ack_frame.frame_type == 2
assert ack_frame.largest_acknowledged == 0x023f
assert ack_frame.ack_delay == 0x0c456789
assert ack_frame.ack_range_count == 0x0f23456789abcdef
assert ack_frame.first_ack_range == 0x0f
assert ack_frame.ack_ranges == b"\x00" * 0xf
assert ack_frame.ect0_count is None
assert ack_frame.ect1_count is None
assert ack_frame.ecn_ce_count is None
assert ack_frame.payload == NoPayload()

= Check build equal to start bytes
assert ack_frame.build() == frame_bytes


+ Ack frame, case 3: type 0x03, just zero bytes
= Parse the bytes
frame_bytes = unhexlify("0300000000000000")
one_ack = FrameStorage(frame_bytes)

= Check only one frame
frames = one_ack.get_frames()
assert len(frames) == 1

= Check that one ack frame
ack_frame = frames[0]
assert type(ack_frame) == AckFrame
assert ack_frame.frame_type == 3
assert ack_frame.largest_acknowledged == 0
assert ack_frame.ack_delay == 0
assert ack_frame.ack_range_count == 0
assert ack_frame.first_ack_range == 0
assert ack_frame.ack_ranges is None
assert ack_frame.ect0_count == 0
assert ack_frame.ect1_count == 0
assert ack_frame.ecn_ce_count == 0
assert ack_frame.payload == NoPayload()

= Check build equal to start bytes
assert ack_frame.build() == frame_bytes


+ Ack frame, case 4: type 0x03, various bytes
= Parse the bytes
frame_bytes = unhexlify(
    "03"
    + "423f"
    + "8c456789"
    + "cf23456789abcdef"
    + "0f"
    + "00" * 0xf
    + "0f"
    + "4678"
    + "8f123456"
)
one_ack = FrameStorage(frame_bytes)

= Check only one frame
frames = one_ack.get_frames()
assert len(frames) == 1

= Check that one ack frame
ack_frame = frames[0]
assert type(ack_frame) == AckFrame
assert ack_frame.frame_type == 3
assert ack_frame.largest_acknowledged == 0x023f
assert ack_frame.ack_delay == 0x0c456789
assert ack_frame.ack_range_count == 0x0f23456789abcdef
assert ack_frame.first_ack_range == 0x0f
assert ack_frame.ack_ranges == b"\x00" * 0xf
assert ack_frame.ect0_count == 0x0f
assert ack_frame.ect1_count == 0x0678
assert ack_frame.ecn_ce_count == 0x0f123456
assert ack_frame.payload == NoPayload()

= Check build equal to start bytes
assert ack_frame.build() == frame_bytes
